JYU-IBA/potku

- widgets/matplotlib/measurement/energy_spectrum.py
- Limit lines no longer stuck on screen after user ignores elements.
- Fixed an issue where ratio could only be calculated when two elements
were originally chosen for the graph.
> Fixed inactive limit Lines

- dialogs/simulation/layer_properties.py
- dialogs/simulation/recoil_element_selection.py
- modules/masses.py
- widgets/measurement/settings.py
> Layer properties now shows the previously selected isotope

- dialogs/energy_spectrum.py
- modules/energy_spectrum.py
- modules/measurement.py
- modules/observing.py
- modules/request.py
- modules/selection.py
- potku.py
- tests/gui/test_gui_utils.py
- tests/unit/test_observing.py
- widgets/gui_utils.py
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/measurement/tab.py
- widgets/simulation/tab.py
- widgets/simulation/target.py
Following things have changed:
- ProgressReporter now has a get_sub_reporter method that returns a new ProgressReporter that can report progress of subtasks
- This replaces various cumbersome starting point and incrementation arguments that were previously given to subtasks
- Also StatusBarHandler is used more throughout the program.
I'll review this change on Mac before merging.
> Subprogress system for easier progress reporting

- modules/depth_files.py
- modules/energy_spectrum.py
- modules/measurement.py
- tests/gui/test_gui_utils.py
- ui_files/ui_profile_settings_tab.ui
- widgets/binding.py
- widgets/gui_utils.py
- widgets/profile_settings.py
Python code now calls tof_list properly. Windows version has some encoding issues.
> Issue 3 tofin toflist b

- dialogs/dialog_functions.py
- dialogs/simulation/recoil_info_dialog.py
- modules/element_simulation.py
- modules/get_espe.py
- modules/math_functions.py
- modules/recoil_element.py
- tests/gui/test_binding.py
- tests/gui/test_optim_params.py
- tests/gui/test_scientific_spinbox.py
- tests/unit/test_math_functions.py
- tests/unit/test_recoil_element.py
- tests/unit/test_request.py
- tests/utils.py
- ui_files/ui_measurement_settings_tab.ui
- ui_files/ui_optimization_fluence_params.ui
- ui_files/ui_scientific_spinbox_widget.ui
- widgets/detector_settings.py
- widgets/input_validation.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/measurement/settings.py
- widgets/scientific_spinbox.py
- widgets/simulation/optimization_parameters.py
- widgets/simulation/optimized_fluence.py
> Issue 41 fluence

- dialogs/global_settings.py
- modules/element_simulation.py
- modules/global_settings.py
- potku.py
- tests/unit/test_global_settings.py
- ui_files/ui_global_settings.ui
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/simulation/point_coordinates.py
- widgets/simulation/tab.py
- widgets/simulation/target.py
> Merge recoil distribution changes to master

- dialogs/measurement/depth_profile.py
- dialogs/measurement/depth_profile_ignore_elements.py
- dialogs/simulation/multiply_area.py
- modules/element.py
- modules/general_functions.py
- modules/recoil_element.py
- tests/gui/test_depth_profile.py
- tests/integration/test_depth_profile_handling.py
- tests/mock_objects.py
- tests/unit/test_depth_files.py
- tests/unit/test_element.py
- tests/unit/test_recoil_element.py
- ui_files/ui_percentage_widget.ui
- widgets/matplotlib/import_timing.py
- widgets/matplotlib/measurement/depth_profile.py
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/matplotlib/mpl_utils.py
- widgets/matplotlib/simulation/composition.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/matplotlib/simulation/recoil_atom_optimization.py
- widgets/simulation/percentage_widget.py
- widgets/simulation/point_coordinates.py
Some more refactoring of RecoilAtomDistribution, PercentageWidget and a pretty major change in MatplotlibDepthProfileWidget.
PR adds some reusable graphing components (VerticalLimitLines, LineChart,  etc) that can be found in `widgets.matplotlib.mpl_utils` module. This is a first proper step at solving #5 .
> Recdist refactor

- dialogs/measurement/settings.py
- dialogs/request_settings.py
- dialogs/simulation/element_simulation_settings.py
- dialogs/simulation/settings.py
- modules/global_settings.py
- tests/gui/test_preset_widget.py
- ui_files/ui_measurement_settings_tab.ui
- ui_files/ui_preset_widget.ui
- ui_files/ui_profile_settings_tab.ui
- ui_files/ui_request_simulation_settings.ui
- widgets/binding.py
- widgets/gui_utils.py
- widgets/measurement/settings.py
- widgets/preset_widget.py
- widgets/profile_settings.py
- widgets/simulation/settings.py
> Issue 27 presets

- dialogs/graph_settings.py
- dialogs/measurement/import_binary.py
- dialogs/measurement/import_measurement.py
- modules/measurement.py
- modules/request.py
- potku.py
> Issues #59, #62, #63

- README.md
> Issues #60, #61

- potku.py
> Fix crash caused by right clicking on empty space in sidebar (#88)

- dialogs/simulation/optimization.py
- ui_files/ui_optimization_params.ui
> Upper X adjusted when checkbox is checked and an element is selected

- widgets/matplotlib/measurement/tofe_histogram.py
> Fix histogram element deletion crash and broken clean up (#104)

- modules/detector.py
- tests/unit/test_detector.py
> Fix adding efficiency files to a measurement that doesn't use request settings (#106)

- widgets/matplotlib/mpl_utils.py
Fixes an issue where depth profile ratios would not be updated immediately after user sets new limits or selects/deselects elements (#113).
> Depth profile ratio update fix

- README.md
> Update Development instructions

- dialogs/measurement/depth_profile_numeric_limits.py
- ui_files/ui_depth_profile_limits.ui
- widgets/matplotlib/measurement/depth_profile.py
Right clicking the depth profile window opens a dialog where one can numerically set the limits
> Add numerical limit selection tool to depth profile

- widgets/matplotlib/calibration/curve_fitting.py
Fixes issue #122  clicking plot with selection tool enabled resets zoom
> Fix selection tool zoom bug in calibration curve fitting 

- dialogs/global_settings.py
- ui_files/ui_global_settings.ui
Added paths of
-Ini-file
-Request
-Used efficiencies
to the global settings.
User can copy the paths for faster access to the files
> Add paths to global settings

- .gitignore
- modules/element.py
- modules/energy_spectrum.py
- widgets/matplotlib/measurement/energy_spectrum.py
Automatically plots the sum spectrum and creates a hist-file to the directory.
> Sum spectrum

- dialogs/simulation/layer_properties.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
Element concentrations of the layers are already set once in the Layer properties dialog. 
This enhancement removes the discomfort of manually setting the concentration values again in the recoil atom distribution view.
> "Export elements" in "Target composition" now sets the correct concentrations to the "Recoil atom distribution"

- dialogs/global_settings.py
- ui_files/ui_global_settings.ui
> Revert "Add paths to global settings"

- .gitignore
- modules/element.py
- modules/energy_spectrum.py
- widgets/matplotlib/measurement/energy_spectrum.py
> Revert "Sum spectrum"

- dialogs/simulation/layer_properties.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
> Revert ""Export elements" in "Target composition" now sets the correct concentrations to the "Recoil atom distribution""

- dialogs/measurement/depth_profile.py
- dialogs/simulation/layer_properties.py
- ui_files/ui_depth_profile_params.ui
- widgets/matplotlib/measurement/depth_profile.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/measurement/tab.py
> Revert "Added possibility to include used efficiency files in depth profile plot"

- ui_files/ui_eff_plot.ui
- ui_files/ui_request_detector_settings.ui
- widgets/detector_settings.py
- widgets/eff_plot.py
- widgets/matplotlib/eff_plot.py
> Revert "Revert "Add possibility to plot eff-files from detector settings""

- dialogs/simulation/layer_properties.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
> Revert "Revert ""Export elements" in "Target composition" now sets the correct concentrations to the "Recoil atom distribution"""

- dialogs/measurement/depth_profile.py
- ui_files/ui_depth_profile_params.ui
- widgets/matplotlib/measurement/depth_profile.py
- widgets/measurement/tab.py
> Revert "Revert "Added possibility to include used efficiency files in depth profile plot""

- dialogs/global_settings.py
- ui_files/ui_global_settings.ui
> Revert "Revert "Add paths to global settings""

- .gitignore
- dialogs/simulation/optimization.py
- modules/nsgaii.py
- ui_files/ui_optimization_fluence_params.ui
- ui_files/ui_optimization_recoil_params.ui
- widgets/simulation/optimization_parameters.py
This is my first pull request for this project. Feel free to comment!
> Option to choose the optimization parameter

- .gitignore
- modules/element.py
- modules/energy_spectrum.py
- widgets/matplotlib/measurement/energy_spectrum.py
> Revert "Revert "Sum spectrum""

- dialogs/measurement/depth_profile.py
> Revert "Optimize verbose checkbox"

- .gitignore
- dialogs/measurement/calibration.py
- ui_files/ui_request_detector_settings.ui
- widgets/detector_settings.py
> Changes detector's calibration angle's comma to dot

- dialogs/energy_spectrum.py
- modules/element_simulation.py
- modules/nsgaii.py
Fixes missing positional argument (verbose) and disables verbose as default + reformat/rearranges the code
> Fixes bug causing the software to crash

- dialogs/measurement/depth_profile.py
- modules/energy_spectrum.py
Hides the warning text in a depth profile window when there are _not_ multiple .cut-files selected.
> Hides the warning text in a depth profile window

- dialogs/measurement/depth_profile.py
- widgets/matplotlib/measurement/depth_profile.py
Changes in checkboxes updates now correctly in the plot.
> Updates depth profile plot correctly

- potku.py
- widgets/detector_settings.py
- widgets/eff_plot.py
> Makes the active window on top

- .gitignore
- dialogs/energy_spectrum.py
> User can now import external files

- .gitignore
- dialogs/measurement/settings.py
- dialogs/simulation/settings.py
- ui_files/ui_measurement_tab.ui
- ui_files/ui_simulation_tab.ui
- widgets/base_tab.py
- widgets/measurement/tab.py
- widgets/simulation/tab.py
> Issue #124

- compile_mac_example.sh
- bump up Python version
- add a notice about non-existent JIBAL directory
- update text
- clone Potku
Closes #183
> Update Mac example instructions

- ui_files/ui_target_widget.ui
- widgets/matplotlib/simulation/recoil_atom_distribution.py
Add also possibility to delete all existing elements when exporting elements from target composition
> Add "delete all elements" button to recoil atom distribution

- dialogs/energy_spectrum.py
- modules/energy_spectrum.py
- modules/enums.py
- tests/gui/test_dialog_initialization.py
- tests/unit/test_energy_spectrum.py
- ui_files/ui_energy_spectrum_params.ui
- widgets/matplotlib/measurement/energy_spectrum.py
- widgets/matplotlib/simulation/element.py
Fix #200, #206, #207 and resolve #201 and #204
> Add a sum spectrum checkbox and "SUM" abbreviation on the plot

- dialogs/energy_spectrum.py
- modules/energy_spectrum.py
- modules/enums.py
- tests/gui/test_dialog_initialization.py
- tests/unit/test_energy_spectrum.py
- ui_files/ui_energy_spectrum_params.ui
- widgets/matplotlib/measurement/energy_spectrum.py
- widgets/matplotlib/simulation/element.py
> Update sum spectrum graph in response to GUI changes

- widgets/detector_settings.py
- widgets/eff_plot.py
> Add a checker that raise an error if there are not cut-files for the selected elements

- modules/general_functions.py
- widgets/measurement/tab.py
- widgets/simulation/tab.py
> Add a new general function that checks the sum spectrum's state 

- modules/get_espe.py
- modules/profile.py
- modules/recoil_element.py
- tests/unit/test_recoil_element.py
Make it easier to maintain density values (FIX: #219). 
Replace #226.
> Define the reference density and the profile density as constants

- dialogs/measurement/depth_profile.py
- ui_files/ui_depth_profile_params.ui
> Show used efficiency files by default

- widgets/matplotlib/measurement/energy_spectrum.py
> Fix sum spectrum issues

- widgets/matplotlib/measurement/energy_spectrum.py
- crash was caused by self.self.
> Fix sum espe crash in measurement (#255)

- dialogs/measurement/import_selection.py
- modules/measurement.py
- modules/selection.py
- ui_files/ui_selection_dialog.ui
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/measurement/tofe_histogram.py
As said in the title, these changes fix issue #253.
Most noticeable changes include creating a new script _dialogs/measurement/import_selection.py_ which handles the dialog that opens up when pressing "_load selections_" button under the ToFe-histogram. New ui-file for the dialog was also created in the folder which contains all of the other ui-files. Also the contents of a couple of functions in the `class Selector` in _modules/selection.py_ were reorganized and tweaked. Other changes were made but are more minor.
> Fixed issue #253

- Pipfile
- dialogs/measurement/depth_profile_numeric_limits.py
- modules/element_simulation.py
- modules/mcerd.py
- modules/observing.py
- modules/optimization.py
- tests/gui/test_gui_utils.py
- tests/mock_objects.py
- tests/unit/test_mcerd.py
- tests/unit/test_observing.py
- ui_files/ui_depth_profile_limits.ui
- widgets/gui_utils.py
- widgets/matplotlib/base.py
- widgets/matplotlib/measurement/depth_profile.py
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/matplotlib/simulation/recoil_atom_distribution.py
- widgets/simulation/controls.py
Updates project to python 3.10. Also updates libraries.
> Python upgrade

- dialogs/simulation/foil.py
- modules/general_functions.py
- modules/selection.py
- widgets/matplotlib/measurement/energy_spectrum.py
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/measurement/tab.py
Main changes:
- Saves spectrums to espectra.hist file
- Corrected measured and simulated spectrum bins to matching positions
- Selection select from legend
- Selection copy and paste from context menu
- Selection editing
> Selection editing

- dialogs/energy_spectrum.py
- dialogs/simulation/foil.py
- dialogs/simulation/recoil_info_dialog.py
- modules/cut_file.py
- modules/energy_spectrum.py
- modules/general_functions.py
- modules/get_espe.py
- modules/selection.py
- potku.py
- ui_files/ui_energy_spectrum_params.ui
- widgets/matplotlib/measurement/energy_spectrum.py
- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/measurement/tab.py
- widgets/simulation/percentage_widget.py
Main changes:
- Fixes ratio tool
- Fixes sum spectrum plotting
- Added remove external file
- correctly format percentages
> Ratio tool fix

- dialogs/measurement/settings.py
- widgets/detector_settings.py
Add support for copying efficiency files over from request settings to measurement-specific settings as a basis for the specific settings.
> Add support to copy eff files to specific settings

- modules/sample.py
- modules/simulation.py
- widgets/matplotlib/measurement/tofe_histogram.py
Fixes the button used to save cuts being disabled after pasting a copied selection. Additionally fix a crash that occurs when pasting irregular clipboard content by CTRL+V shortcut.
> Fix copy paste of histogram selections

- .github/workflows/compile_c_apps.yml
- .github/workflows/package_potku.yml
Fixes a new issue that caused discovery of artifacts from old and current GitHub Actions workflows to fail.
> Fix old and current workflow run artifact discovery.

- dialogs/measurement/angle_calibration.py
- modules/angle_calibration.py
- ui_files/ui_angle_calibration_dialog.ui
- widgets/detector_settings.py
- widgets/matplotlib/calibration/angle_selector.py
Added automatic angle calibration, changed angle calibration offset to [channel] units and removed unused code
> Added automatic angle calibration

- dialogs/dialog_functions.py
- modules/depth_files.py
- widgets/matplotlib/measurement/depth_profile.py
- widgets/matplotlib/measurement/energy_spectrum.py
Removes tight_layout to show whole legend box in energy spectrum widget
> Energy spectrum scaling fix

- widgets/matplotlib/measurement/tofe_histogram.py
When editing selection and calculating mid_points, there can be float values, that break things elsewhere. These will now be converted to integers when calculated.
> Bug fixes 202309

- dev/Automatic_packaging_README.md
- dev/build.bat
- dev/build.sh
- external/Makefile
This adds functionality to copy dynamic libraries of GSL from the build system to the Potku package for each OS.
> Include gsl dynamic lib to package

- widgets/matplotlib/measurement/tofe_histogram.py
- widgets/simulation/controls.py
Fixed bug in zoom function in Tofe-histogram. Cause of bug was not checking for active zoom in __on_motion and on_release methods.
ElementSimulation class shows simulation type scatter in simulation header as "Scatter".
> Bugfixes 202310

- widgets/matplotlib/calibration/angle_selector.py
Angle calibration widget calculates calibration in same format as is used in input fields
> Angle calibration fix
