dialogs/dialog_functions.py
dialogs/measurement/selection.py
dialogs/simulation/layer_properties.py
dialogs/simulation/recoil_element_selection.py
modules/calibration.py
modules/element.py
modules/masses.py
modules/mcerd.py
tests/gui/test_gui_utils.py
tests/gui/test_isotope_selection.py
tests/gui/test_measurement_settings.py
tests/gui/test_scientific_spinbox.py
tests/mock_objects.py
tests/unit/test_element.py
tests/unit/test_masses.py
widgets/binding.py
widgets/gui_utils.py
widgets/isotope_selection.py
widgets/matplotlib/calibration/curve_fitting.py
widgets/matplotlib/measurement/element_losses.py
widgets/matplotlib/measurement/tofe_histogram.py
widgets/measurement/settings.py

This PR makes some changes to the masses module. Element class now acts as the main interface to the module. The idea is to simplify the loading of isotopes to various comboboxes. 
There is also an initial implementation of a IsotopeSelectionWidget that is meant to be a reusable component to handle all isotope selections. Currently the widget is only used in LayerProperties dialog.

Masses rewrite

---

dialogs/energy_spectrum.py
dialogs/measurement/depth_profile.py
dialogs/measurement/element_losses.py
modules/measurement.py
widgets/gui_utils.py

This commit moves the fill_cuts_treewidget function from measurement module to gui_utils module. This way we can get rid of PyQt references in measurement module

fill_cuts_treewidget function moved to gui_utils module

---

modules/measurement.py
potku.py

Instead of measurement module importing Selector from modules.selection (and therefore also importing matplotlib and PyQt), selector's class is provided as a parameter for Measurement's
add_measurement_file method. The allows the caller to decide which kind of Selector is being used, making the backend GUI independent.

Hard coded Selector dependency removed from measurement module

---

build.bat
build.sh
modules/get_espe.py

- Updates to newest versions of Jibal and MCERD. Bugfixes in both. 
- Removed files.txt and assignments.txt from Jibal
- MCERD requires a minimum version of Jibal now, not just any version.
- MCERD outputs its version to stderr and also Jibal version (both headers / library). Easier to check version mismatches.
- Fixes build issues with MCERD if Jibal is already installed to e.g. /usr/local.
- Calculation issues related to fluence and density in get_espe.py and get_espe itself fixed. All code now agrees on units of 1/cm3 for density.
- Get_espe also outputs -density in old units (1/cm2) for first 10 nm

MCERD and Jibal update, including fluence related bugfixes

---

Pipfile
README.md
potku.spec

No more missing binaries when creating the bundle (except for libgsl which still needs to be installed separately for non-Windows versions).
Not tested on macOS which is usually the most finicky OS when it comes to running pyinstaller, so stuff may break.
Closes #61.

#61 spec file updates

---

modules/global_settings.py

Effects of this PR:
- Older (before d0fe3a7) versions of Potku no longer crash when trying to use .ini files that were produced by newer (1b5f398 and after) versions of Potku.
- Versions between d0fe3a7 and 1b5f398 cannot read color schemes from .ini files made by older or newer versions of Potku, but will revert to default value without crashing.
Closes #79.

Revert color scheme serialization back to the original way (#79)

---

modules/element_simulation.py
modules/simulation.py
tests/integration/test_element_simulation.py
tests/unit/test_element_simulation.py

- fix ElementSimulation not copying request settings on creation (continuation to #80)
- update get_mcerd_params and remove unused methods

Elem sim settings copy

---

modules/base.py
modules/energy_spectrum.py
modules/get_espe.py
tests/mock_objects.py
tests/resource/cuts.1H.ERD.0.cut
tests/resource/cuts.1H.ERD.1.cut
tests/resource/cuts.35Cl.RBS_Mn.0.cut
tests/resource/cuts.7Li.0.0.0.cut
tests/unit/test_energy_spectrum.py

`energy_spectrum` module now uses `subprocess_utils.process_output` function to parse energy spectrum data. Also added type hints and refactored other parts of the module. Tests and some resource files also included.

energy_spectrum module uses subprocess_utils

---

Pipfile.lock

Pipfile.lock regenerated on Windows using `pipenv lock`. With this update I was able to run `pipenv install` on Linux without having to comment out Windows dependencies in the Pipfile.
Someone should test this on Mac before accepting the PR.

Update Pipfile.lock (#111)

---

.gitignore
dialogs/measurement/depth_profile.py
modules/measurement.py
tests/unit/test_element_simulation.py
tests/unit/test_foil.py
tests/unit/test_measurement.py
tests/unit/test_parsing.py
tests/unit/test_simulation.py
tests/utils.py

Closes #114 
There is another bug though; when measurement uses request settings, the reference density set in the Depth Profile dialog has no effect. The value defined in Request Settings dialog is used instead.

Fix AttributeError when selecting x axis unit (#114)

---

dialogs/measurement/depth_profile.py
modules/depth_files.py
modules/enums.py
modules/general_functions.py
modules/measurement.py
modules/request.py
tests/gui/test_depth_profile.py
tests/gui/test_depth_profile_dialog.py
tests/gui/test_dialog_initialization.py
tests/integration/test_depth_profile_handling.py
tests/mock_objects.py
tests/unit/test_general_functions.py
tests/unit/test_mcerd.py
tests/unit/test_observing.py
ui_files/ui_depth_profile_params.ui
widgets/matplotlib/measurement/depth_profile.py
widgets/matplotlib/simulation/element.py
widgets/measurement/tab.py

Fixes #119.
Other changes:
- binding module used extensively to bind GUI values to Python properties in DepthProfileDialog
- depth profile x axis units are now an enum
- adds a small backwards compatibility fix for requests made with older versions of Potku (97755ae)

Make reference density setting work for measurement's that use request settings

---

README.md
build.sh
compile_mac_example.sh

Current JIBAL version and MCERD versions were updated in PR #42. This PR updates JIBAL to 0.3.0 and MCERD to 1.0.4.
MCERD has some bugfixes:
- Some warnings have been moved to stderr from stdout, this caused issues since Potku did not expect these messages: https://github.com/JYU-IBA/mcerd/commit/3c69de9242cac185ec0fad0549abfcb0595b4f98
- `get_angle()` returned wrong values at the extremes of impact parameter, which caused unphysical behaviour, although extremely rarely.  Also there is a new option to disable MC scattering steps: https://github.com/JYU-IBA/mcerd/commit/2a85f5ec26a589e469a8a4afd58a63b30fa2ba72
JIBAL has mostly small feature improvements, performance improvements and lots of small bugfixes, which didn't affect use with Potku. Newest version of JIBAL is required by MCERD. …

Update MCERD and JIBAL to latest versions.

---

dialogs/energy_spectrum.py
dialogs/measurement/depth_profile.py
dialogs/measurement/element_losses.py
dialogs/measurement/import_measurement.py
dialogs/new_request.py
modules/calibration.py
modules/depth_files.py
modules/element_simulation.py
modules/energy_spectrum.py
modules/general_functions.py
modules/measurement.py
modules/profile.py
modules/request.py
modules/run.py
modules/selection.py
modules/simulation.py
modules/ui_log_handlers.py
potku.py
tests/integration/test_element_simulation.py
tests/unit/test_element_simulation.py
tests/unit/test_logging.py
tests/unit/test_request.py
tests/utils.py
widgets/base_tab.py

Major changes in this PR:
- Adds a unified `Logger` interface for Requests, Measurements and Simulations. From now on, logging should be done via this interface rather than invoking Python's logging module.
- Makes sure that each `Logger` uses its own log files. Previously all Requests that were opened during the runtime of the program would end up writing to the same file. This was also the case for Measurements and Simulations that had the same name. This fixes #93.
- Uses uuid module to create unique names for each `Logger`. Also uses period separated names to establish a parent - child hierarchy between Requests and Measurements/Simulations.

Refactor logging, fixes #93

---

dialogs/simulation/layer_properties.py
ui_files/ui_layer_dialog.ui

Pressing the button checks the values of the other amount-spinboxes and sets the value of the current spinbox so that the sum of the amounts is is either 1 or 100.

Add sum button to simulation layer properties

---

dialogs/dialog_functions.py
dialogs/energy_spectrum.py
dialogs/file_dialogs.py
dialogs/measurement/import_measurement.py
dialogs/measurement/load_measurement.py
modules/detector.py
widgets/detector_settings.py
widgets/matplotlib/measurement/tofe_histogram.py

Functions in `dialogs.file_dialogs` now return Path objects as expected by the backend code. Loading detector settings from file no longer cause a crash (#132).
Changing the return types also affected other parts of the code so there are quite a few changes beside the bug fix.
Type hints have been added and docstrings have been updated.

Fix a crash when loading detector settings + type hints and stuff

---

.gitignore
dialogs/measurement/calibration.py

- Saves ToF-calibration graph as pkl-file and loads it (and modifications) when the calibration tab is opened.  Before the user had to accept points again / separately to plot the graph again.  
- Fixes QTimer

Saves and shows automatically ToF-calibration graph + Fixes QTimer

---

.gitignore
modules/measurement.py
ui_files/ui_depth_profile_params.ui

The user could not expand the window size when viewing the depth profile windows. Filenames are often (too) long and not in alphabetical order. The window did not expand correctly.

Expands depth profile's window and sorts cut files + elemental losses

---

.gitignore
widgets/matplotlib/simulation/recoil_atom_distribution.py
widgets/simulation/target.py

It saves when the user, for example, moves those points.

Save target and element simulations automatically when user makes changes

---

widgets/matplotlib/measurement/depth_profile.py
widgets/matplotlib/mpl_utils.py

Removes unused element symbol from the legend if it is not included in plot nor the ratio calculation

Removes element letters from the depth profile legend 2

---

modules/nsgaii.py
tests/gui/test_optim_params.py

Fluence and recoil have different initialization which caused a conflict between boolean values

Fix unittest and removes an unnecessary function

---

modules/element_simulation.py

`verbose` didn't have a default value when it should have.
Fixes `ElementSimulation.calculate_espe()` calls and `TestElementSimulation.test_calculate_spectrum()`.
This pull request is a cherry-picked version of #176.

Fix parameter verbose in calculate_espe

---

tests/unit/test_logging.py

- macOS returns a symlinked temp directory

Fix test_logger_returns_paths_to_log_files (#190)

---

dialogs/global_settings.py
modules/get_espe.py
modules/global_settings.py
modules/recoil_element.py

User can now set the default reference density in the global settings. The density is stored in potku2.ini file like the other global parameters. 4.98e22 is still the initial value but now it can be changed by user.

Make default reference density user configurable in global settings

---

widgets/matplotlib/measurement/energy_spectrum.py

Fix #221 :
- Add different line styles for sum spectra
- Define the line width for sum spectra
- Draw sum spectra on top (Zorder)

Improve sum spectrum readability

---

widgets/detector_settings.py
widgets/eff_plot.py

This PR fixes the issue #250 where efficiency plots weren't working by basically making two changes. 
- First change was changing [EfficiencyDialog](https://github.com/JYU-IBA/potku/blob/master/widgets/eff_plot.py#L39) from `QWidget` to `QDialog` so that `exec_` could be called
- Second change was to fix the files being plotted. Potku was trying to plot files from the last folder the user used when they added new efficiency files but this might cause crashes and other problems. Now it tries to plot files from `<request>/Default/Detector/Efficiency_files`

Fixed efficiency plot

---

dialogs/simulation/optimization.py
modules/enums.py
modules/linear_optimization.py
modules/nsgaii.py
modules/optimization.py
ui_files/ui_optimization_fluence_params.ui
ui_files/ui_optimization_linear_fluence_params.ui
ui_files/ui_optimization_linear_recoil_params.ui
ui_files/ui_optimization_params.ui
ui_files/ui_optimization_recoil_params.ui
widgets/matplotlib/simulation/recoil_atom_optimization.py
widgets/simulation/optimization_linear_parameters.py
widgets/simulation/optimization_parameters.py
widgets/simulation/optimized_fluence.py
widgets/simulation/optimized_recoils.py

Issue: #193
TODO:
Future TODO:

Add linear optimization to Optimize Recoils or Fluence

---

modules/linear_optimization.py
ui_files/ui_optimization_linear_fluence_params.ui
ui_files/ui_optimization_linear_recoil_params.ui
widgets/simulation/optimization_linear_parameters.py

Issue: #193
- improved optimization accuracy: `numpy.polyfit` is far better than `scipy.interpolate.interp1d`
- improved optimization stability: doesn't need monotonous sampled values anymore
- prominences are used for statistical weights instead of as cut-off values
- added user-selectable fitting polynomial degree
Done (from task list):
Future TODO:

Linear optimization improvements

---

dialogs/simulation/element_simulation_settings.py
widgets/matplotlib/simulation/element.py

FIX: #245 and REPLACE: #246
Note that there is an old commit 8a265464a65c0870c9c8c0305247a4eca11e708c and its revert. However they should not affect anything.

Highlight an element settings button when not using request setting values

---

dialogs/simulation/optimization.py
modules/element_simulation.py
modules/linear_optimization.py

Issue: #193
Done (from task list):
Future TODO:
The less significant recoil in `ElementSimulation.calculate_espe()` is either `self.optimization_recoils[0]` or `self.get_main_recoil()`. That one is only used to get the **.erd** data file name. The passed `recoil_element` argument is used for the **.recoil** name and contents (recoil point locations). I just added a dummy `ElementSimulation.optimization_recoils` list object to get around this multi-recoil issue in initial sampling. This could be done more elegantly, but it should work.
I changed the default optimization to *Linear & recoil*.

Linear optimization improvements2

---

modules/get_espe.py
modules/profile.py
modules/recoil_element.py

Remove unnecessary GlobalSettings inits, use GlobalSettings.DEFAULT_REF_DENSITY as default argument for reference_density. Remove unnecessary REFERENCE_DENSITY constant from profile.py.

Remove unnecessary GlobalSettings inits

---

widgets/matplotlib/simulation/recoil_atom_distribution.py

There was a broken for loop used to delete secondary recoils. Additionally the loop was reachable only when a simulation was running. Both of these problems are fixed with.

Fix secondary recoil deletion bug when deleting main recoil

---

modules/element.py
modules/sample.py
modules/simulation.py
widgets/matplotlib/simulation/recoil_atom_distribution.py

Fix crash that occurs in MCERD by pressing the export elements button on the target tab. Crash occured due to the exported elements not having a set recoiltype type, so I set the default value of an element object's RRectype to "REC". Also fix a follow-up bug where simulations break if user doesn't view the recoil atom distribution tab after exporting, but before closing Potku.
Also fixes new simulations not showing up by changing the sought filetype from .simulation to .mccfg.

Fix element export crash and new simulations

---

modules/sample.py
modules/simulation.py

I noticed that when not using request settings on the simulation side, the settings were not saved properly due to `modules/simulation.py` function `to_file` being commented out completely. Saving is fixed by adding few lines that use the `ConfigManager` class to save the actual simulation data and uncommenting the lines corresponding to simulation specific settings.
Additionally in PR #295 I changed the discovery of simulation files to be tied to .mccfg files instead of .simulation files. This lead to a problem with discovering old simulations that don't yet have a .mccfg file in them. I changed the discovery to look for both .simulation and .mccfg files and to break the for file loop once either one is dicovered in order to prevent one simulation being discovered twice.

Fix simulation specific settings and simulation discovery

---

modules/simulation.py
widgets/matplotlib/simulation/composition.py
widgets/simulation/tab.py

Fixes multiple saving-related issues.
Firstly on MCERD side opening saved widgets of energy spectra caused Potku to crash as occasionally Path objects were created from empty strings, which point to current folder, i.e.  Path('') is basically pointing to directory ./. This caused crashing issues.
Secondly frequently changing settings in MCERD side relating to the target could lead to a situation where Potku tries to delete a non-existent file. I put the deletion in a try-expect block to prevent crashing + nuking the target due to the crash.
Finally there was an issue, where if multiple simulations were open simultaneously, the saving of the simulations could save the settings to a wrong file. This was fixed by properly updating the file where config_manager is pointed to in the to_file …

Fix more saving issues

---

dialogs/dialog_functions.py
modules/depth_files.py
widgets/matplotlib/measurement/depth_profile.py

Writes used efficiency files to used_eff_files.txt and uses that to display actually used eff files in depth profile as "files used" instead of "files found" that is used otherwice.

Show actually used eff file

---

modules/element_simulation.py
modules/recoil_element.py
modules/simulation.py
potku.py
tests/unit/test_recoil_element.py
widgets/detector_settings.py
widgets/matplotlib/simulation/element.py
widgets/matplotlib/simulation/recoil_atom_distribution.py
widgets/simulation/settings.py
widgets/simulation/target.py

This PR addresses various issues, of which the foremost is probably the inability to create new Requests. As Potku now uses the new more focused .mccfg filetype for Simulations, various methods for writing the old filetypes were commented out and disabled. Despite the new .mccfg filetype, Potku still utilizes the old file types in the Default directory of a request. These defaults couldn't be created properly due to the disabled to_file methods of various objects. I enabled the required old to_file methods again with some checks for Default directory and commented out calls where they aren't needed anymore. Additionally renaming simulations still created a .simulation file instead of .mccfg, so I remedied that.
I also fixed some tests about the serialization of ElementSimulation objects. …

Fix new request and serialization issues

---

.github/workflows/compile_c_apps.yml
.github/workflows/package_potku.yml
.github/workflows/version_bump.yml

This changes the different third-party actions referred via version tags, to be referred via commit hashes for better security.

Pin the GitHub actions references via hashes instead of tags.

---

.github/workflows/package_potku.yml
README.md
README_macOS.txt
external/Potku-erd_depth/Makefile
external/Potku-tof_list/Makefile
potku.spec

I noticed some issues with the compilation of the C apps (tof_list and erd_depth specifically) in the automatic packaging process. In the logs there were errors about undefined references and not finding header files. On Linux there was problems with linking math.h and on macOS there was an issue about finding gsto_masses.h.
I fixed these issues in the makefiles by setting the compiler argument -lm as the last one and fixing a bad indentation in the depend rule, which is used to link the dependencies.
Additionally PyInstaller version isn't pinned anywhere and it recently updated to version 6.0.0, which caused some packaging issues. I pinned the PyInstaller version in package_potku.yaml file to 5.13.2 and also wrote it in the README.md.
Finally I added a README_macOS.txt to be bundled in …

Fix makefile and packaging issues

---

widgets/matplotlib/measurement/tofe_histogram.py

Should use selection.id to identify selection, not index of selections, as there might be changes to selections that cause index to be out of bounds etc.

Use selection.id, not index of selections

---

dialogs/request_settings.py
widgets/detector_settings.py

Element simulations were resetting needlessly when changing both request-wide settings or specific settings. This happened due to ScientificSpinBox values for ToF slope, ToF offset, angle offset and angle slope in detector settings in detector settings being initialized with zero value and only after initialization was the actual value from the detector object set in the fields. This caused the change tracking feature to trigger and think that there were changes that require resetting simulations.
This was fixed by initializing the field values with required values, instead of setting them later.
Additionally fixes an issue, where detector settings didn't save after closing request settings dialog. In the function that is called upon clicking ok in the dialog, there was no call to save …

Fix simulation resetting settings changes

---

modules/request.py
modules/simulation.py
widgets/detector_settings.py
widgets/simulation/controls.py

- Circumvent issues with ElementSimulation objects being inserted into Default.simulation file.
-  Expand naming checks of simulation control widgets to include synonyms of ERD element simulation type.
- Remove tracking of changes for angle_slope and angle_offset in Detector settings.
-  Remove multiplication and division operations of angle_offset in Detector settings upon loading and saving the value.

Hotfixes 06112023

---

widgets/matplotlib/measurement/tofe_histogram.py

When creating first selection and editing points Tofe-histogram crashes for not finding start_points attribute. Added initialization to None in class init.

Added start_point initialization to None at init

---

ui_files/ui_foil_widget.ui
widgets/detector_settings.py
widgets/foil.py
widgets/matplotlib/measurement/energy_spectrum.py
widgets/matplotlib/simulation/composition.py

Set minimum value of distance spinboxes in detector foil widget to 0.01 mm to avoid issues in simulation. Additionally initialize the spinbox values to minimum.
Remove query about removing efficiency files in detector settings tab. Now the x button just directly removes a particular efficiency file from detector's efficiency directory.
Fix issue with energy spectra area ratios. Removed calculations that force the area ratio to [0, 1] interval. Additionally all energy spectra are handled in the same fashion.
Fix crashing issues when modifying, deleting or adding layers in FoilWidget in detector settings.

Hotfixes 15112023

---

dialogs/measurement/depth_profile.py
modules/enums.py
widgets/measurement/tab.py

Windows uses simple character sets in some languages which doesn't include '²'-character. It is better to use just plain '2' in save file and use from_string method to read input.

Fixes depth profile file character error in simple character sets

---

widgets/measurement/tofe_histogram.py
widgets/simulation/target.py

On MacOS the ToFE histogram and target widgets were closeable despite is_closaeble attribute being set to False. To circumvent this issue the closeEvent function for these widgets was overridden and set to instead just minimize the widgets. Has no effect on Windows side of things.

Fix closing of ToFE histogram and target widgets on MacOS

---

README.md

Potku (Python) did pass filenames correctly to MCERD, but the filenames referenced inside these files (detector configuration, detector foil configuration) did not work.
This PR also contains an unrelated update to README.

MCERD update to support spaces in filenames
